### PR TITLE
Spawn Room & New Terrain

### PR DESCRIPTION
**Pull request by Tmac4930**
- Added Spawn Room Asset to in-build Desert Scene
- Made edits to the terrain.
- Created Worm bones prefab.

### CODE REVIEW

**Comment by luke-goldfain** [comment]
Afraid this might cause issues with shaders, but it looks like you at least haven't touched the checkpoint prefabs themselves yet.

**Comment by Tmac4930** [comment]
It's fine for now I'm sure

**Comment by luke-goldfain** [comment]
> It's fine for now I'm sure
It definitely will not be fine if shaders break as a result of this merge and we have to figure out why. I'm checking that now.

**Comment by luke-goldfain** [comment]
Checked and all is well, no problems that I know of. The new layout looks great

**Pull request merged**
